### PR TITLE
Resonance blog post.

### PR DESCRIPTION
**Pull request by moorepants**
@ixjlyons I've started a blog post that is required to finish out the CEE grant. I'll be pecking at it over the next couple of weeks. Can you contribute some text on the homeworks, server, and any other relevant items. Feedback and edits on any of it is appreciated. It will be cross posted to my blog and the EELC blog.

# Tasks

- [x] Add some kind of image, embed, or view of a notebook.
- [x] Add an image showing off a homework problem.
- [ ] Provide example of computational thinking in vibrations (maybe)
- [x] Screenshot of our Jupyterhub service

### CODE REVIEW

**Comment by ixjlyons** [comment]
Sure. Is this the final project report (due April 18) or a separate requirement due sooner?

**Comment by moorepants** [comment]
We promised a EELC blogpost in the proposal, but also require a final report. I think that if we make this complete, I'll only need add a few details about the budget, etc to call it a report. So this should be sufficient for both.

**Comment by moorepants** [comment]
I have a SciPy abstract that may be useful to pull from for this: https://github.com/moorepants/SCIPY2018/blob/master/abstract.rst

**Comment by ixjlyons** [comment]
Do I have permissions to push here? Or do you want me to just follow up once you're done? I've only passed through it once and made some spelling/grammar stuff, but I pushed it to my fork for backup.

**Comment by moorepants** [comment]
You can make a pull request against this branch and I can merge it. I think I'll not add permissions since it is my personal website.

**Comment by moorepants** [comment]
@ixjlyons this is getting pretty close now, can you give me some text for the sections you are most familiar with

**Comment by ixjlyons** [comment]
Sounds good. I'll be on it this week.

**Comment by moorepants** [comment]
@ixjlyons Any updates?

**Comment by moorepants** [comment]
@ixjlyons thanks for the edits. i added some tasks at the top, mainly to add in some visuals to the post. Feel free to help with those.

I'm going to publish by this weekend. Going to give a talk on things in the post Monday to the education department.

**Pull request merged**
